Dev
inventaire-des-orgues/portail pull request #530
Opened 2021-07-25 16:56 UTC by CelestinHuet

2021-07-27 21:40 UTC, patou requested changes
La branche n'est pas à jour par rapport à Master.

Il pourrait être intéressant d'avoir un bouton pour réinitialiser les filtres.

2021-07-27 21:40 UTC, patou commented on orgues/templates/orgues/carte.html
> +    <b style="font-size: x-large;">Les orgues</b>
Je pense que l'on devrait voir le terme filtrer dans le titre.

2021-07-27 21:40 UTC, patou commented on orgues/templates/orgues/carte.html
> +    <form id="filtre_formulaire" style="margin-left: 15px;" action="" >
C'est pas une bonne chose de mettre du css dans l'attribut style.

2021-07-27 21:40 UTC, patou commented on orgues/templates/orgues/carte.html
> +  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
Tous les autres scripts sont copié dans le projet et non téléchargé via un autre site.

2021-07-27 21:40 UTC, patou commented on orgues/templates/orgues/carte.html
> +        $( "#jeu-range" ).html("Nombre de jeux : " + ui.values[ 0 ] + " - " + ui.values[ 1 ] );
Ce code est dupliqué ligne 221

2021-07-27 21:40 UTC, patou commented on orgues/templates/orgues/carte.html
> +        $( "#claviers-range" ).html("Nombre de claviers : " + ui.values[ 0 ] + " - " + ui.values[ 1 ] );
De même ce code est dupliqué ligne 241

2021-07-27 21:40 UTC, patou commented on orgues/views.py
> +    JSON renvoyant la liste des orgues correspondant aux conditions à droite de la carte
JSON renvoyant la liste des orgues correspondant aux conditions de filtre envoyé.

2021-07-27 21:40 UTC, patou commented on orgues/templates/orgues/carte.html
> +          data_filtre[$("input[name='"+element+"']").val()] = true;
En HTTP, tu peux faire passer des listes de valeurs : 
data_filter['etat[]'] = $("input[name='"+element+"']").val()

Et dans python, tu peux faire : 
request.GET.getlist('etat')

Tu récupère ainsi directement une liste.

2021-07-28 19:14 UTC, closed without merging

2021-07-28 20:27 UTC, patou commented
@CelestinHuet je pense que tu as fais une erreur en fermant la MR ?

2021-07-28 20:35 UTC, CelestinHuet commented
@patou J'en ai créé une nouvelle avec les améliorations que j'ai ajoutées tout à l'heure.

2021-07-28 20:47 UTC, patou commented
@CelestinHuet tes commits était aussi ajouté dans cette MR.

Après, comme tu fais une MR qui merge la branche dev vers master mais du coup il y a beaucoup de modification en même temps. 
Il aurait fallut faire simplement une branche pour juste modifier les filtres.