Filtre de la carte
inventaire-des-orgues/portail pull request #531
Opened 2021-07-28 19:15 UTC by CelestinHuet

2021-07-28 22:37 UTC, patou requested changes
Bravo pour l'amélioration en cours du code.

Encore d'autres remarques.

2021-07-28 22:37 UTC, patou commented on orgues/views.py
Tu peux utiliser un Serializer pour transformer ton objet orgue en l'objet que tu as besoin : 

```suggestion
        return JsonResponse(OrgueCarteSerializer(list(queryset), many=True).data, safe=False)
```

Et voici un début d'implémentation de 
```python
class OrgueCarteSerializer(serializers.ModelSerializer):
    """
    Serializers utilisé pour constuire l'index de recherche
    """
    facteurs = serializers.SerializerMethodField()
    nombre_jeux = serializers.SerializerMethodField()

    class Meta:
        model = Orgue
        fields = [
            "slug",
            "latitude",
            "longitude",
            "commune",
            "emplacement",
            "edifice",
            "references_palissy",
            "nombre_jeux",
            "resume_composition",
            "etat",
            "facteurs"
        ]

    def get_nombre_jeux(self, obj):
        return obj.jeux_count

    def get_facteurs(self, obj):
        facteurs = []
        seen_facteurs = set()
        evenements = Evenement.objects.filter(orgue=obj, facteurs__isnull=False).prefetch_related('facteurs').order_by('annee')
        for evenement in evenements:
            nouveau_facteur = " & ".join(evenement.facteurs.values_list('nom', flat=True))
            if nouveau_facteur not in seen_facteurs:
                seen_facteurs.add(nouveau_facteur)
                facteurs.append(nouveau_facteur)
        return ", ".join(facteurs)
```
(reste à gérer le format des facteurs avec l'id du facteur et le type d'évènement).

2021-07-29 13:38 UTC, CelestinHuet commented
@patou Merci pour les remarques, elles sont très instructives.

`etat_filter = $('input[name="etat"]:checked').map(() => $(this).val()).get();` : je n'arrive pas à faire fonctionner cette ligne, donc je n'ai pas touché à ce passage.

Pour le champ "non renseigné" des claviers, si on le supprime, on ne peut plus afficher tous les orgues. Il me semble préférable de laisser ce champ.

2021-07-29 17:30 UTC, patou commented
> @patou Merci pour les remarques, elles sont très instructives.

Pour le serialiazer j'ai donné rapidement le code, mais pour les facteurs il faut pas serialiazer dans une chaîne de caractère pour refaire un Split ensuite dans le code js.
Il faut directement le mettre sous forme de tableau dans le code python. (J'avais juste copier le serialiazer qui permet d'indexer orgue) 

> `etat_filter = $('input[name="etat"]:checked').map(() => $(this).val()).get();` : je n'arrive pas à faire fonctionner cette ligne, donc je n'ai pas touché à ce passage.
> 

J'ai pas tester le code, mais quel est l'erreur ?

C'est montrer le principe du Map plutôt que faire un each et ajouter à chaque fois dans un tableau.

> Pour le champ "non renseigné" des claviers, si on le supprime, on ne peut plus afficher tous les orgues. Il me semble préférable de laisser ce champ.

Je comprend.

2021-07-29 20:35 UTC, patou commented on orgues/templates/orgues/carte.html
> +        classes: $('#classes').is(':checked'),
sans accent classés n'est pas très lisible, j'utiliserais plutôt le terme "mh"

2021-07-29 21:16 UTC, patou requested changes
Encore des améliorations possibles.

2021-07-29 21:16 UTC, patou commented on orgues/templates/orgues/carte.html
> +      return composition_filter;
```suggestion
      const claviers = $('input[name="clavier"]:checked').map((_, item) => $(item).val()).get();
      return $("input[name='Pedalier']").is(':checked') ? claviers.concat(claviers.map(item => item + "/P")) ? : claviers;
```

2021-07-29 21:16 UTC, patou commented on orgues/templates/orgues/carte.html
> +    )
```suggestion
        update_jeu_range();
        update_filter();
      }
    });

   function update_jeu_range() {
        $( "#jeu-range" ).html( 
          "Nombre de jeux : " + $( "#slider-range" ).slider( "values", 0 ) + " - " +  $( "#slider-range" ).slider( "values", 1 ) 
        )
    }
    update_jeu_range();
```

2021-07-29 21:16 UTC, patou commented on orgues/templates/orgues/carte.html
>        </form>
```suggestion
          <input type="reset" value="Réinitialiser" class="btn btn-primary rounded-pill mt-3 btn-block" />
      </form>
```

2021-07-30 14:09 UTC, patou approved these changes

2021-08-04 19:42 UTC, merged